server:
  port: 8081
jwt:
  secret: fasdfasdfsdfsdsdffdsfdssdfaddafdsffdsasdfdfsadsfadfdsfdsadfsfdasfdasdfsasfsasdfsdasfafasdsadasfddfasdfa
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/proyecto2
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
      logging:
         level:
          org:
            hibernate:
              SQL: DEBUG